version: "3.8"

services:
  database:
    container_name: database
    image: postgres:12.17-alpine
    restart: always
    environment:
      - POSTGRES_USER=myipam
      - POSTGRES_PASSWORD=myipam
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: